### ISSUE TITLE
props attribute is null when declaring child component inside parent component

### ISSUE THREAD

**Issue by Dan-Do** [ficusjs/ficusjs#10]
Hi @ducksoupdev,
Please look at this code
```javascript
import { html, renderer } from 'https://cdn.skypack.dev/@ficusjs/renderers@4/htm'
import { createCustomElement, createComponent } from 'https://cdn.skypack.dev/ficusjs'

createCustomElement('hello-world', {
  renderer,
  state() {
    return {me: {name: 'ficusjs', type: 'javascript'}}
  },
  handleClick (e) {
    window.alert('Hello to you!')
  },
  childComponent: createComponent('comp-child', {
    props: {parent: {type: Object, required: true, observed: false}, foo: {type: Object, required: true, observed: false}},
    render () {
      return html`<p>Hello ${this.props.foo.name}</p>`
    }
  }),
  render () {
    return html`
      <div>
        <comp-child parent=${this} foo=${this.state.me}></comp-child>
        <button type="button" onclick="${this.handleClick}">Click me</button>
      </div>
    `
  }
})
```
`this.state.me` has value but cannot be transfered to child's props.
By the way, what is the better way to communicate between parent and child (child is declared inside of parent)? Without using event-bus to subcribe. I use `parent=${this}` as property but haven't test it.

**Comment by ducksoupdev** [comment]
Hi @Dan-Do, components cannot be nested in this way. Each component registers itself with the CustomElementRegistry using the provided tag and must be created independently and not in a nested way.

In terms of parent -> child communication, the child can omit events that the parent listens for. The other way around, a parent can invoke child methods by obtaining a reference to the child and calling methods directly. The alternative communication method is using the event bus.

**Comment by Dan-Do** [comment]
Hi @ducksoupdev
Even though I moved the child component outside, it still didn't work
```javascript
createComponent('comp-child', {
  props: {foo: {type: Object, required: true, observed: false}},
  render () {
    return html`<p>Hello ${this.props.foo.name}</p>`
  }
})
createCustomElement('hello-world', {
  renderer,
  state() {
    return {me: {name: 'ficusjs', type: 'javascript'}}
  },
  render () {
    return html`
      <div>
        <comp-child parent=${this} foo=${this.state.me}></comp-child>
        <button type="button" onclick="${this.handleClick}">Click me</button>
      </div>
    `
  }
})
```
Niether this `<comp-child parent=${this} foo=${()=>{return {name: 'ficusjs', type: 'javascript'}}}></comp-child>`

**Comment by ducksoupdev** [comment]
I wouldn't recommend passing the parent component to the child. Passing it as an attribute automatically converts the value to a string (hence the `[object object]`). 

Depending on the renderer used, you can pass complex objects like arrays and objects to components but I wouldn't recommend this for elements themselves.

It's hard to see what you are trying to achieve from your example. Can you create a Codepen and post the link together with a description of what you want to do? That would really help :)

**Comment by Dan-Do** [comment]
Hi @ducksoupdev
Let say I want to create a Modal dialog, it needs an object to populate a form for editing.
In the document, it's written that the type of `props`
```
This must be one of String, Number, Boolean or Object
```
I wonder how to pass Object as props (without JSON.stringify it)?

**Comment by ducksoupdev** [comment]
This is achieved using an appropriate renderer. The [`lit-html`](https://docs.ficusjs.org/renderers/) and [`uhtml`](https://docs.ficusjs.org/renderers/) renderers allow you to pass complex structures to components in this way. You can pass objects or arrays. Both of these use a dot prefix which tells the renderer to pass the value as a property rather than using an attribute. This will create an instance of the child and then pass the property to it. Your above example would look like this:

```js
render () {
  return html`<ul class="todo-list">
    ${this.store.getters.todos.map(t => html`<todo-item .todo="${t}"></todo-item>`)}
  </ul>`
}
```

I have created a Codepen as an example - https://codepen.io/ducksoupdev/pen/zYEVpVd?editors=1010

The caveat with using the dot prefix to pass complex data to a component is that you cannot set the prop as required because the value is passed once the child component has been instantiated. Prop validation happens during this initialization phase so required props will cause an error if not passed in as an attribute.

**Comment by Dan-Do** [comment]
Hi @ducksoupdev
I modified your example on this link https://codepen.io/ali33yukisakura/pen/JjrgRXK?editors=1011
If you open the console on that codepen, there is error `"The required prop 'pages' has no value set"`, though it's still rendered ok. But on my machine, it says `Uncaught TypeError: can't access property "length", this.props.pages is null`, so nothing rendered.

**Comment by ducksoupdev** [comment]
As I mentioned in my previous message, required props are evaluated when instantiated which means they won't work when passing complex variables as these are passed after the component is instantiated.

It is recommended to use attributes for simple variables and a store for sharing complex variables between multiple components.

**Comment by ducksoupdev** [comment]
Not having the ability to use the required props for complex objects isn't limiting. You can handle empty props in components with placeholders and visual alerts and other logic.

**Comment by ducksoupdev** [comment]
Happy to have a look at your app if you can share a Github link?

**Comment by Dan-Do** [comment]
I set up a testing environment for you. Please visit http://app.4phuong.pro:1988
Sign in using username: demo, password: test
Texts are in Vietnamese, the css layout is not completed, so just ignore it.
Happy debugging :)

**Comment by ducksoupdev** [comment]
> 

Thanks for the codepen. I'll take a look as soon as I can.

**Comment by ducksoupdev** [comment]
I have run your codepen locally and I am struggling to see what you are trying to do. The components you have created and how you have structured it is causing it to crash. This is down to the structure of what you have created and how you are using it.

If you could describe the problem you are trying to solve, I am happy to help create a solution using the components in the way they are designed?

**Comment by Dan-Do** [comment]
Hi @ducksoupdev
I don't want to use `router`, so I have an idea that:
- Let's say I have 5 `views` which has its own route (`/view-1` ... `/view-5`)
- There is a `global state` to store the loaded views and current active route. Each view is created using `withStore(global_state)`.
- When the website is first loaded, `view-1` is shown automatically.
- There is a sidebar which contains 5 buttons to load approriate views when clicked.
- Assume `view-3` is clicked, then `view-1` is just hidden (add css display: none). And `view-2` is shown (remove css display: none).
- Whenever views are switched around, `setState` is called on the global store, which makes the recursive loop of render I think.
My codepen above is a reduced example of this idea :)

**Comment by Dan-Do** [comment]
BTW, if you view the console log of that codepen, you will see that the message `rendered` is doubled shown each time a link is clicked.

**Comment by ducksoupdev** [comment]
I have created a codepen that matches your description. 

https://codepen.io/ducksoupdev/pen/VwrzjJd

Components are registered with the CustomElementRegistry so must be statically declared. This can be done using a creator function as shown in the codepen.

**Comment by Dan-Do** [comment]
Thanks @ducksoupdev, that's a smart solution which solve the recursion. My app is slightly different that it just create the views on the fly when user click on the left sidebar. I will do that and get back to you on next couple days.

**Comment by Dan-Do** [comment]
Hi @ducksoupdev,

When debugging my app without using your solution, I detect that this line https://github.com/ficusjs/ficusjs-state/blob/e5aff994876be02050858f39f763bf2a2e7bb674/src/store.mjs#L243 causes the recursive.
For testing, I changed it to `if (!this.callbacks.includes(callback)) this.callbacks.push(callback)` then this issue does not happen anymore.
I hope you can look at this and accept the change in your source code.

Best regards.

**Comment by ducksoupdev** [comment]
@Dan-Do happy to review and make that change. I'll let you know the outcome shortly.

**Comment by Dan-Do** [comment]
That's great. Thank you very much.
