### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by melikyants** [ficusjs/ficusjs#11]
[This package](https://www.jsdelivr.com/package/npm/ficusjs) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by ducksoupdev** [comment]
@melikyants the package is an ES module so the target is set for that use. It does not provide a UMD module so the `jsdelivr` and `browser` properties are not set in the `package.json` file. The `main` field is set but is not recognised by `jsDelivr` as the others are not set.

I would recommend using Skypack - https://www.skypack.dev/view/ficusjs
