### ISSUE TITLE
docs.ficusjs.org layout glitch

### ISSUE THREAD

**Issue by mateatslc** [ficusjs/ficusjs#12]
I looked, but still not sure if this is the right repo for reporting this (for the same reason I couldn't submit a PR)...

Anyways, I realized that a CSS custom property named `--navbar-height` is missing from the docs site, causing the left nav bar to scroll along with the main content. That makes it super annoying to traverse the docs.

![Screenshot 2022-05-24 at AM 11 05 15](https://user-images.githubusercontent.com/590577/169994673-07a9a7d2-6044-41cf-9fa7-5799cb4aca08.png)

Setting it by hand fixes the layout, not sure where it is being lost.

**Comment by ducksoupdev** [comment]
@mateatslc thanks for letting me know. This will be fixed in a release due very shortly.
