### ISSUE TITLE
AppState proxy + nested prop

### ISSUE THREAD

**Issue by Spope** [ficusjs/ficusjs#4]
Hi,

I think the Application State proxy only works when we mutate a top level property as it is not recursive. I tried to mutate a nested property by direct assignment and my component were not updated. Using the setState method works.

Here is a link to a [codepen](https://codepen.io/Spope/pen/ZEezBaJ?editors=1010).

I don't know if a recursive proxy would be to much, maybe a mention of this in the documentation could be enought ?

Thanks for this library it rocks !

**Comment by ducksoupdev** [comment]
@Spope thanks for letting us know. You are right that only top level property changes are reactive when mutated. The docs aren't clear on the difference between direct assignment and using the `setState` method. We'll make sure the docs are updated to make it clearer.

**Comment by ducksoupdev** [comment]
The documentation has now been updated - https://docs.ficusjs.org/components/#direct-assignment
