### ISSUE TITLE
how to use w/ npm?

### ISSUE THREAD

**Issue by cekvenich2** [ficusjs/ficusjs#6]
I like that it works on CDN! A lot.

But I also build cordova, so I need to be able to use w/ npm. What is the npm version of this?

```
import { html, renderer } from 'https://cdn.skypack.dev/@ficusjs/renderers@3/htm'
import { createCustomElement } from 'https://cdn.skypack.dev/ficusjs@3/custom-element'
```

(aside I use snowpack, it is ok).

**Comment by ducksoupdev** [comment]
I have added a Snowpack starter repo that you can clone and use - https://github.com/ficusjs/ficusjs-snowpack-starter. Give it a go and let me know how you get on :+1:

**Comment by cekvenich2** [comment]
Nice. THANK YOU MUCH!
Aside, I'll be using it with my project: http://AXthe.net
