### ISSUE TITLE
WithStore hook crashed logic of component load

### ISSUE THREAD

**Issue by zavada123** [ficusjs/ficusjs#67]
If use withStore and withEventBus, "mounted" component hook run before "created" component hook.

Versions:
- withStore from https://cdn.skypack.dev/ficusjs@6
- createComponent and withEventBus from https://cdn.jsdelivr.net/npm/ficusjs@6.2.1/dist/index.mjs

**Comment by ducksoupdev** [comment]
@zavada123 thanks for letting us know of this issue. This has now been fixed in v6.3.0 - https://github.com/ficusjs/ficusjs/blob/6.3.0/CHANGELOG.md
