### ISSUE TITLE
How to get input fields (and values) in the slot

### ISSUE THREAD

**Issue by cekvenich2** [ficusjs/ficusjs#7]
A common pattern I use w/ raw custom element: my-form
where the input fields are in the slot. 
I want to get values in the fields so that I can call REST/POST.

Here is how this would be handled without custom elements: 
```
			const data = {}
			const fdata = new FormData(document.getElementById('mailFrm'))
			for (var [key, value] of fdata.entries()) {
				data[key] =value;
			}
			console.log(JSON.stringify(data))
```

How would I do this using ficus? Get input values so I can call REST?

**Comment by cekvenich2** [comment]
For example: https://github.com/43081j/shadow-dom-utils or https://javascript.info/slots-composition

**Comment by ducksoupdev** [comment]
You can pass the input fields to your component. The component will render them into a default or named slot.

See this codepen for an example - https://codepen.io/ducksoupdev/pen/zYwqjXY?editors=1011

**Comment by cekvenich2** [comment]
Very nice! Thank you.
